import assert from 'node:assert/strict'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const website = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourceRoot = resolve(website, '../src')
const printer = ts.createPrinter({ removeComments: true })
const parsed = new Map()

async function source(path) {
  if (!parsed.has(path)) {
    parsed.set(
      path,
      ts.createSourceFile(
        path,
        await readFile(path, 'utf8'),
        ts.ScriptTarget.Latest,
        true
      )
    )
  }
  return parsed.get(path)
}

async function declaration(path, name) {
  const file = await source(path)
  for (const node of file.statements) {
    if (
      (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) &&
      node.name.text === name
    ) {
      return printer.printNode(ts.EmitHint.Unspecified, node, file)
    }
    if (
      ts.isExportDeclaration(node) &&
      node.moduleSpecifier &&
      node.exportClause &&
      ts.isNamedExports(node.exportClause)
    ) {
      const specifier = node.exportClause.elements.find(
        (item) => item.name.text === name
      )
      if (specifier) {
        return declaration(
          resolve(dirname(path), `${node.moduleSpecifier.text}.ts`),
          specifier.propertyName?.text ?? name
        )
      }
    }
  }
  throw new Error(`Missing public type ${name} in ${path}`)
}

const entry = await source(resolve(sourceRoot, 'index.ts'))
const excerpts = []
for (const node of entry.statements) {
  if (
    !ts.isExportDeclaration(node) ||
    !node.isTypeOnly ||
    !node.moduleSpecifier ||
    !node.exportClause ||
    !ts.isNamedExports(node.exportClause)
  )
    continue
  const module = resolve(
    sourceRoot,
    `${node.moduleSpecifier.text}${node.moduleSpecifier.text === './NitroWebView' ? '.tsx' : '.ts'}`
  )
  for (const specifier of node.exportClause.elements) {
    excerpts.push(
      `## ${specifier.name.text}\n\n\`\`\`ts\n${await declaration(module, specifier.propertyName?.text ?? specifier.name.text)}\n\`\`\`\n`
    )
  }
}

for (const korean of [false, true]) {
  const introduction = korean
    ? 'Package root에서 내보낸 타입을 실제 소스에서 생성한 발췌입니다. Import와 의존 타입은 생략했습니다. 복사해 쓰는 전체 모듈이 아닙니다.\n\n컴포넌트의 공개 탐색 콜백은 `boolean | Promise<boolean>`을 반환합니다. Props·수명·플랫폼 동작은 [Props](./props.md), [Methods](./methods.md), [Events](./events.md)에서 확인하세요.'
    : 'These excerpts come from the types exported at the package root. Imports and dependency types are omitted; this is not a standalone module to copy.\n\nThe public navigation callback returns `boolean | Promise<boolean>`. Read [props](./props.md), [methods](./methods.md), and [events](./events.md) for behavior, lifecycle, and platform restrictions.'
  const document = `<!-- Generated by npm run reference:generate. -->\n\n# Types\n\n${introduction}\n\n${excerpts.join('\n')}`
  const path = resolve(
    website,
    `content/${korean ? 'ko/' : ''}reference/types.md`
  )
  if (process.argv.includes('--write')) await writeFile(path, document)
  else
    assert.equal(
      await readFile(path, 'utf8'),
      document,
      `Public types changed. Run npm run reference:generate in website (${path}).`
    )
}
console.log(
  `${excerpts.length} public type excerpts match the library exports in both languages.`
)
